# **Ingest Data Process**

## Dependencies and Parameters

In [1]:
import pandas as pd

In [2]:
path = "/Users/andrebezerra/Desktop/Dev/DesafiosCodeElevate/diario_de_bordo/info_transportes.csv"
parquet_path = "/Users/andrebezerra/Desktop/Dev/DesafiosCodeElevate/diario_de_bordo/transportes.parquet"

In [4]:
df = pd.read_csv(path, sep=";")
display(df)

# Salvar no formato Parquet (compatível com Delta Lake)
df.to_parquet(parquet_path, engine="pyarrow", index=False)

print("Dados normalizados e salvos em formato Parquet com sucesso!")

,DATA_INICIO,DATA_FIM,CATEGORIA,LOCAL_INICIO,LOCAL_FIM,DISTANCIA,PROPOSITO
0,01-01-2016 21:11,01-01-2016 21:17,Negocio,Fort Pierce,Fort Pierce,51,Alimentação
1,01-02-2016 01:25,01-02-2016 01:37,Negocio,Fort Pierce,Fort Pierce,5,NaN
2,01-02-2016 20:25,01-02-2016 20:38,Negocio,Fort Pierce,Fort Pierce,48,Entregas
3,01-05-2016 17:31,01-05-2016 17:45,Negocio,Fort Pierce,Fort Pierce,47,Reunião
4,01-06-2016 14:42,01-06-2016 15:49,Negocio,Fort Pierce,West Palm Beach,637,Visita ao cliente
...,...,...,...,...,...,...,...
1148,12-31-2016 1:07,12-31-2016 1:14,Negocio,Karchi,Karchi,7,Reunião
1149,12-31-2016 13:24,12-31-2016 13:42,Negocio,Karchi,Unknown Location,39,Parada temporária
1150,12-31-2016 15:03,12-31-2016 15:38,Negocio,Unknown Location,Unknown Location,162,Reunião
1151,12-31-2016 21:32,12-31-2016 21:50,Negocio,Katunayake,Gampaha,64,Parada temporária
1152,12-31-2016 22:08,12-31-2016 23:51,Negocio,Gampaha,Ilukwatta,482,Parada temporária

Dados normalizados e salvos em formato Parquet com sucesso!